postgresql:
  enabled: true
  global:
    postgresql:
      postgresqlPassword: admin
      postgresqlUsername: admin
      postgresqlDatabase: atm-microservices-db
      auth:
        postgresqlPassword: admin
        postgresqlUsername: admin
        username: "admin"
        password: "admin"
        database: "atm-microservices-db"
      servicePort: 4004
      service:
        ports:
          postgresql: "4004"
  auth:
    username: "admin"
    password: "admin"
    database: "atm-microservices-db"

  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false