postgresql:
  enabled: true
  global:
    postgresql:
      postgresqlPassword: admin
      postgresqlUsername: admin
      postgresqlDatabase: atm-microservices-db
      auth:
        username: "admin"
        password: "admin"
        database: "atm-microservices-db"
      servicePort: 4004

  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false