apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atm-account-management-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default #maintain
  source:
    repoURL: https://github.com/amt-richard-bouaro/atm-charts.git
    path: account-helm-deployment/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: atm-microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true