apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amt-richard-bouaro/atm-charts.git
    path: argo-cd/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: atm-microservices
  syncPolicy:
    automated:
      selfHeal: true