apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atm-kafka
  namespace: atm-microservices
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: HEAD
    chart: kafka
    helm:
      valueFiles:
        - kafka/values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: atm-microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true