apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atm-kafka-broker
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: atm-microservices
spec:
  project: default
  source:
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    helm:
      values: |-
        replicaCount: 3
        service:
          name: atm-kafka
          type: ClusterIP
          port: 9092
        persistence:
          enabled: true
          size: 2Gi
  destination:
    namespace: atm-microservices
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true