apiVersion: v2
name: atm-log-management-service
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: mongodb
    version: "13.0.0"  # Choose a stable version here
    repository: "https://charts.bitnami.com/bitnami"

