
# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: amtrbouaro/atm-log-management-service
  pullPolicy: IfNotPresent
  tag: "latest"

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

#This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  create: true # Specifies whether a service account should be created
  automount: true # Automatically mount a ServiceAccount's API credentials?
  annotations: {} # Annotations to add to the service account
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  name: atm-log-management-service
  type: NodePort #ClusterIP
  port: 8885
  targetPort: 8885
  nodePort: 32885

#This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 80

mongodb:
  fullnameOverride: atm-log-management-service-mongodb-server
  auth:
    enabled: true
    rootPassword: secretPassword
    username: admin
    password: adminPassword
    database: atm-log-management-service-mongodb
  primary:
    persistence:
      enabled: true
      storageClass: standard
      size: 4Gi

env:
  EUREKA_SERVER_DEFAULT_ZONE: http://atm-discovery-server.atm-microservices.svc.cluster.local:8882/eureka/
  EUREKA_INSTANCE_HOSTNAME: atm-discovery-server.atm-microservices.svc.cluster.local
  ZIPKIN_TRACING_ENDPOINT: http://atm-zipkin.atm-microservices.svc.cluster.local:9411
  SERVICE_NAME: atm-log-management-service
  SERVER_PORT: 8885
  CONFIG_SERVER_URL: "http://atm-config-server.atm-microservices.svc.cluster.local:8881"
  SPRING_PROFILES_ACTIVE: "log-management-service-dev"
  KAFKA_SERVERS: "atm-kafka.atm-microservices.svc.cluster.local:9092"

  # MongoDB Configuration
  MONGODB_USERNAME: "admin"
  MONGODB_PASSWORD: "adminPassword"
  MONGODB_HOST: atm-log-management-service-mongodb-server
  MONGODB_PORT: 27017
  MONGODB_DATABASE: "atm-log-management-service-mongodb"
